---
title: Aanpassen van Minecraft met Python
hero_image: images / banner.png
description: Navigeer door de wereld van Minecraft Pi, leer met code te creëren en blaas dingen op met TNT
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmeren-0
interests: "spellen"
technologies: "python, minecraft"
site_areas: ""
steps:
  - 
    title: Introductie
  - 
    title: Wat heb je nodig
  - 
    title: Ga de Minecraft-wereld binnen
  - 
    title: Het besturen van Minecraft met Python
  - 
    title: TNT
