---
title: Aanpassen van Minecraft met Python
hero_image: images/banner.png
description: Navigeer door de wereld van Minecraft Pi, leer met code te creëren en
  blaas dingen op met TNT
listed: false
copyedit: false
version: 3
last_tested: 2018-11-21
steps:
- title: Inleiding
  completion: engaged
- title: Ga de Minecraft-wereld binnen
- title: Het besturen van Minecraft met Python
  completion: internal
- title: TNT
