title: Modding Minecraft with Python
hero_image: images/banner.png
description: Navigate the world of Minecraft Pi, learn to create with code and blow things up with TNT
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: programming-0
interests: "games"
technologies: "python, minecraft"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Enter the Minecraft world
  - title: Controlling Minecraft with Python
  - title: TNT
