---
title: Minecraft mit Python verändern
hero_image: images/banner.png
description: Navigiere in der Welt von Minecraft Pi, lerne, mit Code etwas zu erstellen und mit TNT in die Luft zu jagen
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: jam
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps: 
-
title: Einleitung
-
title: Was du brauchen wirst
-
title: Komme in die Minecraft-Welt
-
title: Minecraft mit Python steuern
-
title: TNT