---
title: Faire des modifs de Minecraft avec Python
hero_image: images/banner.png
description: Naviguez dans le monde de Minecraft Pi, apprenez à créer avec du code et faites exploser les choses avec TNT
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0
interests: "games"
technologies: "python, minecraft"
site_areas: ""
steps:
  - 
    title: Introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Entrez dans le monde de Minecraft
  - 
    title: Contrôler Minecraft avec Python
  - 
    title: TNT
