---
title: Personnaliser Minecraft avec Python
hero_image: images/banner.png
description: 'Naviguez dans le monde de Minecraft: Pi, apprenez à créer avec du code
  et faites tout sauter avec du TNT'
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: jam
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Ce dont vous aurez besoin
- title: Entrez dans le monde de Minecraft
  completion: internal
- title: Contrôlez Minecraft avec Python
- title: TNT
