---
title: Controllare Minecraft con Python
hero_image: images/banner.png
description: 'Naviga nel mondo di Minecraft: Pi, impara a creare con i codici e fai esplodere le cose con il TNT'
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0
interests: "games"
technologies: "python"
site_areas: ""
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Entra nel mondo di Minecraft
  - 
    title: Controllare Minecraft con Python
  - 
    title: TNT
